export const SEARCH_ARTICLE_REQUEST = "SEARCH_ARTICLE_REQUEST"
export const SEARCH_ARTICLE_SUCCESS = "SEARCH_ARTICLE_SUCCESS"
export const SEARCH_ARTICLE_FAILURE = "SEARCH_ARTICLE_FAILURE"

export const ALL_ARTICLE_REQUEST = "ALL_ARTICLE_REQUEST"
export const ALL_ARTICLE_SUCCESS = "ALL_ARTICLE_SUCCESS"
export const ALL_ARTICLE_FAILURE = "ALL_ARTICLE_FAILURE"

export const CATEGORY_ARTICLE_REQUEST = "SEARCH_REQUEST"
export const CATEGORY_ARTICLE_SUCCESS = "SEARCH_SUCCESS"
export const CATEGORY_ARTICLE_FAILURE = "SEARCH_FAILURE"

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const SET_USER_PREFERENCES_REQUEST = 'SET_USER_PREFERENCES_REQUEST'
export const SET_USER_PREFERENCES_SUCCESS = 'SET_USER_PREFERENCES_SUCCESS'
export const SET_USER_PREFERENCES_FAILURE = 'SET_USER_PREFERENCES_FAILURE'
export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS'

